---
name: semantic-release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Action | Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9.12.2
        with:
          build: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"