name: Version Python Package

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v9.12.2
